# =========================
# General paths and folders
# =========================
paths:
  project_root: "."       # Root of the project (absolute or relative)

  data:
    scans: "data/scans"   # Pseudo-scans (JPG) created by the scan imitator

    processed:
      ocr_root:    "data/processed/ocr"      # Output of OCR (TXT files)
      tables_root: "data/processed/tables"   # ETL tables (ocr.parquet, features.parquet, labels.csv)
      metrics_root: "data/processed/metrics" # Metrics and statistics (OCR, model evaluation)

    generators:            # Names of generator subfolders for each document type
      bom:                "BOMS"
      quality_checklist:  "QUALITY_CHECKLISTS"
      daily_report:       "DAILY_REPORTS"
      inspection_report:  "INSPECTION_REPORTS"
      maintenance_log:    "MAINTENANCE_LOGS"
      product_data_sheet: "PRODUCT_DATA_SHEETS"

    scans:                 # Scan folders for each level of difficulty
      docs:
        level1:  "data/scans/docs/level1"
        level2:  "data/scans/docs/level2"
        level3:  "data/scans/docs/level3"
      technical_drawings: "data/scans/technical_drawings"

    test: "data/test"       # Test data folder (optional)

    models:                 # Paths to model weights and vectorizers
      cnn_doc_type_classifier: "models/cnn_doc_type_classifier"
      cnn_doc_vs_drw:         "models/cnn_doc_vs_drw"
      lr_doc_vs_drw:
        easy_ocr: "models/lr_doc_vs_drw/easy_ocr"
        tesseract_ocr: "models/lr_doc_vs_drw/tesseract_ocr"
      lr_doc_type_classifier:
        easy_ocr:      "models/lr_doc_type_classifier/easy_ocr"
        tesseract_ocr: "models/lr_doc_type_classifier/tesseract_ocr"
      rule_based_classifier:
        easy_ocr:      "models/rule_based_classifier/easy_ocr"
        tesseract_ocr: "models/rule_based_classifier/tesseract_ocr"

    ocr_results: "data/ocr_results"   # Optional folder for OCR statistics and logs

  tests:
    input:    "tests/input"          # Folder for test input files
    output:   "tests/output"         # Folder for test output files
    metadata: "tests/metadata.csv"   # Metadata logging for test runs

  poppler:
    bin_path: "C:/poppler/Library/bin"  # Path to Poppler binaries for PDF→Image


# =========================
# Generator settings
# =========================
generator_settings:
  default:                         # Used for training datasets
    num_documents: 1
    output_folder: "data/raw"      # Database for training the models

  test:                            # Used for test pipelines
    num_documents: 1
    output_folder: "tests/test_data/test_docs"  # Database to test the models


# =========================
# Scan imitator settings
# =========================
augmentation:
  levels:

    level1:                       # Light augmentation, clean scans
      pdf:
        dpi: 300
      process_image:
        resize_scale: 0.95

        # --- contrast / brightness --- 
        contrast_probability: 0.3
        contrast_range: [1.0, 1.15]
        brightness_probability: 0.3
        brightness_range: [0.95, 1.05]

        # --- crop ---
        crop_probability: 0.1
        crop_max_offset: [10, 10]

        # --- rotate ---
        rotate_probability: 0.1
        rotate_angle_range: [-1.5, 1.5]
        rotate_180_probability: 0.0

        # --- noise ---
        noise_probability: 0.1
        noise_std_range: [0.3, 0.8]

        # --- vertical streak ---
        vertical_streak_probability: 0.05
        vertical_streak_width_min: 10
        vertical_streak_width_max: 30
        vertical_streak_intensity_min: 0.97
        vertical_streak_intensity_max: 1.02

        # --- dust ---
        dust_probability: 0.05
        dust_count: 50
        dust_max_radius: 1

        # --- motion blur ---
        motion_blur_probability: 0.1
        motion_blur_size_options: [3, 5]
        motion_blur_directions: ["horizontal", "vertical"]

        # --- page warp ---
        page_warp_probability: 0.05
        page_warp_amplitude: [0.5, 1.0]

        # --- crumple map ---
        crumple_map_probability: 0.05
        crumple_map_std: 2
        crumple_map_blur_kernel: [51, 51]

        # --- vignette ---
        vignette_probability: 0.05
        vignette_strength: 0.2
        inverse_vignette_probability: 0.1

        # --- textures ---
        paper_texture_probability: 0.5
        paper_texture_paths:
          - "textures/paper1.jpg"
          - "textures/paper2.jpg"
        paper_texture_opacity: 0.15
        paper_texture_scale: 1.0

        # --- JPEG quality ---
        jpeg_quality_range: [80, 95]

    level2:                       # Medium degradation
      pdf:
        dpi: 300
      process_image:
        resize_scale: 0.85

        contrast_probability: 0.8
        contrast_range: [1.1, 1.4]
        brightness_probability: 0.8
        brightness_range: [0.85, 1.0]

        crop_probability: 0.5
        crop_max_offset: [40, 40]

        rotate_probability: 0.4
        rotate_angle_range: [-4, 4]
        rotate_180_probability: 0.07

        noise_probability: 0.4
        noise_std_range: [1.0, 2.5]

        vertical_streak_probability: 0.4
        vertical_streak_width_min: 15
        vertical_streak_width_max: 60
        vertical_streak_intensity_min: 0.92
        vertical_streak_intensity_max: 1.05

        dust_probability: 0.3
        dust_count: 200
        dust_max_radius: 2

        motion_blur_probability: 0.6
        motion_blur_size_options: [5, 7, 9]
        motion_blur_directions: ["horizontal", "vertical"]

        page_warp_probability: 0.5
        page_warp_amplitude: [1.0, 2.5]

        crumple_map_probability: 0.5
        crumple_map_std: 5
        crumple_map_blur_kernel: [101, 101]

        vignette_probability: 0.1
        vignette_strength: 0.4
        inverse_vignette_probability: 0.4

        paper_texture_probability: 1
        paper_texture_paths:
          - "data/assets/textures/paper1.jpg"
          - "data/assets/textures/paper2.jpg"
          - "data/assets/textures/paper3.jpg"
        paper_texture_opacity: 0.3
        paper_texture_scale: 1.0

        jpeg_quality_range: [55, 85]

    level3:                       # Heavy degradation, worst-case OCR
      pdf:
        dpi: 200
      process_image:
        resize_scale: 0.75

        contrast_probability: 0.95
        contrast_range: [0.9, 1.6]
        brightness_probability: 0.95
        brightness_range: [0.75, 1.1]

        crop_probability: 0.8
        crop_max_offset: [120, 120]

        rotate_probability: 0.8
        rotate_angle_range: [-10, 10]
        rotate_180_probability: 0.2

        noise_probability: 0.8
        noise_std_range: [2.5, 5.0]

        vertical_streak_probability: 0.7
        vertical_streak_width_min: 25
        vertical_streak_width_max: 90
        vertical_streak_intensity_min: 0.85
        vertical_streak_intensity_max: 1.15

        dust_probability: 0.6
        dust_count: 500
        dust_max_radius: 3

        motion_blur_probability: 0.8
        motion_blur_size_options: [7, 9, 11, 13]
        motion_blur_directions: ["horizontal", "vertical", "diag"]

        page_warp_probability: 0.8
        page_warp_amplitude: [2.0, 4.0]

        crumple_map_probability: 0.8
        crumple_map_std: 8
        crumple_map_blur_kernel: [151, 151]

        vignette_probability: 0.4
        vignette_strength: 0.6
        inverse_vignette_probability: 0.5

        paper_texture_probability: 1
        paper_texture_paths:
          - "data/assets/textures/paper1.jpg"
          - "data/assets/textures/paper2.jpg"
          - "data/assets/textures/paper3.jpg"
        paper_texture_opacity: 0.45
        paper_texture_scale: 1.2

        jpeg_quality_range: [25, 55]


# =========================
# OCR settings
# =========================
tesseract_ocr:
  lang: "eng"
  pdf_dpi: 300
  image_extensions: ['.jpg','.jpeg','.png','.tiff','.bmp']
  pdf_extension: '.pdf'
  max_dim: 800
  tesseract_cmd: "C:/Program Files/Tesseract-OCR/tesseract.exe"

easy_ocr:
  lang:
    - en
  pdf_dpi: 300
  image_extensions: ['.jpg','.jpeg','.png','.tiff','.bmp']
  pdf_extension: '.pdf'
  max_dim: 1024


# =========================
# Doc-vs-Drw classifier settings
# =========================
doc_vs_drw_classifier:
  tfidf:
    stop_words:    "english"
    max_features:  5000
  train_test_split:
    test_size:    0.2
    stratify:     true
    random_state: 41
  logistic_regression:
    max_iter:     500
    solver:       "lbfgs"
    class_weight: "balanced"
    random_state: 41


# =========================
# Doc type classifier settings
# =========================
doc_type_classifier:
  tfidf:
    max_features: 1000
    stop_words:   null
  train_test_split:
    test_size:  0.2
    stratify:   true
    random_state: 41
  logistic_regression:
    max_iter:     1000
    solver:       "lbfgs"
    multi_class:  "auto"
    class_weight: "balanced"
    random_state: 41


# =========================
# Sampling settings
# =========================
sampling:
  docs_per_subfolder: 100

# =========================
# Main pipeline settings
# =========================
defaults:
  ocr_engine: "easy_ocr"
  vsd_classifier: "cnn"
  doc_classifier: "tfidf_lr"
  level: "level3"