#--- general structure and paths ---#
paths:
  project_root: "."
  data:
    raw: "data/raw"
    generators:
      bom:                "BOMS"
      quality_checklist:  "QUALITY_CHECKLISTS"
      daily_report:       "DAILY_REPORTS"
      inspection_report:  "INSPECTION_REPORTS"
      maintenance_log:    "MAINTENANCE_LOGS"
      product_data_sheet: "PRODUCT_DATA_SHEETS"
    scans:
      docs:
        level1:  "data/scans/docs/level1"
        level2:  "data/scans/docs/level2"
        level3:  "data/scans/docs/level3"
      technical_drawings: "data/scans/technical_drawings"
    extracted:
      tesseract_ocr:
        level1:  "data/extracted/tesseract_ocr/level1"
        level2:  "data/extracted/tesseract_ocr/level2"
        level3:  "data/extracted/tesseract_ocr/level3"
        technical_drawings: "data/extracted/tesseract_ocr/technical_drawings"
      easy_ocr:
        level1:  "data/extracted/easy_ocr/level1"
        level2:  "data/extracted/easy_ocr/level2"
        level3:  "data/extracted/easy_ocr/level3"
        technical_drawings: "data/extracted/easy_ocr/technical_drawings"
    test: "data/test"
    models:
      cnn_doc_type_classifier: "data/models/cnn_doc_type_classifier"
      cnn_doc_vs_drw: "data/models/cnn_doc_vs_drw"
      lr_doc_vs_drw: "data/models/lr_doc_vs_drw"
      lr_doc_type_classifier:
        easy_ocr:      "data/models/lr_doc_type_classifier/easy_ocr"
        tesseract_ocr: "data/models/lr_doc_type_classifier/tesseract_ocr"
      rule_based_classifier:
        easy_ocr:      "data/models/rule_based_classifier/easy_ocr"
        tesseract_ocr: "data/models/rule_based_classifier/tesseract_ocr"
    ocr_results: "data/ocr_results"
  tests:
    input:    "tests/input"
    output:   "tests/output"
    metadata: "tests/metadata.csv"
  poppler:
    bin_path: "C:/poppler/Library/bin"


#--- generator settings ---#
generator_settings:
  default:
    num_documents: 300
    output_folder: "data/raw" # database for traning the models
  test:
    num_documents: 5
    output_folder: "tests/test_data/test_docs"  # database to test the models with new data


#--- scan imitator settings ---#
augmentation:
  levels:

    level1:
      pdf:
        dpi: 300
      process_image:
        resize_scale: 0.95

        #--- contrast / brightness ---# 
        contrast_probability: 0.3
        contrast_range: [1.0, 1.15]
        brightness_probability: 0.3
        brightness_range: [0.95, 1.05]

        #--- crop ---#
        crop_probability: 0.1
        crop_max_offset: [10, 10]

        #--- rotate ---#
        rotate_probability: 0.1
        rotate_angle_range: [-1.5, 1.5]
        rotate_180_probability: 0.0

        #--- noise ---#
        noise_probability: 0.1
        noise_std_range: [0.3, 0.8]

        #--- vertical streak ---#
        vertical_streak_probability: 0.05
        vertical_streak_width_min: 10
        vertical_streak_width_max: 30
        vertical_streak_intensity_min: 0.97
        vertical_streak_intensity_max: 1.02

        #--- dust ---#
        dust_probability: 0.05
        dust_count: 50
        dust_max_radius: 1

        #--- motion blur ---#
        motion_blur_probability: 0.1
        motion_blur_size_options: [3, 5]
        motion_blur_directions: ["horizontal", "vertical"]

        #--- page warp ---#
        page_warp_probability: 0.05
        page_warp_amplitude: [0.5, 1.0]

        #--- crumple map ---#
        crumple_map_probability: 0.05
        crumple_map_std: 2
        crumple_map_blur_kernel: [51, 51]

        #--- vignette ---#
        vignette_probability: 0.05
        vignette_strength: 0.2
        inverse_vignette_probability: 0.1

        #--- textures ---#
        paper_texture_probability: 0.5
        paper_texture_paths:
          - "textures/paper1.jpg"
          - "textures/paper2.jpg"
        paper_texture_opacity: 0.15
        paper_texture_scale: 1.0

        #--- JPEG quality ---#
        jpeg_quality_range: [80, 95]

    level2:
      pdf:
        dpi: 300
      process_image:
        resize_scale: 0.85

        contrast_probability: 0.8
        contrast_range: [1.1, 1.4]
        brightness_probability: 0.8
        brightness_range: [0.85, 1.0]

        crop_probability: 0.5
        crop_max_offset: [40, 40]

        rotate_probability: 0.4
        rotate_angle_range: [-4, 4]
        rotate_180_probability: 0.07

        noise_probability: 0.4
        noise_std_range: [1.0, 2.5]

        vertical_streak_probability: 0.4
        vertical_streak_width_min: 15
        vertical_streak_width_max: 60
        vertical_streak_intensity_min: 0.92
        vertical_streak_intensity_max: 1.05

        dust_probability: 0.3
        dust_count: 200
        dust_max_radius: 2

        motion_blur_probability: 0.6
        motion_blur_size_options: [5, 7, 9]
        motion_blur_directions: ["horizontal", "vertical"]

        page_warp_probability: 0.5
        page_warp_amplitude: [1.0, 2.5]

        crumple_map_probability: 0.5
        crumple_map_std: 5
        crumple_map_blur_kernel: [101, 101]

        vignette_probability: 0.1
        vignette_strength: 0.4
        inverse_vignette_probability: 0.4

        paper_texture_probability: 1
        paper_texture_paths:
          - "textures/paper1.jpg"
          - "textures/paper2.jpg"
          - "textures/paper3.jpg"
        paper_texture_opacity: 0.3
        paper_texture_scale: 1.0

        jpeg_quality_range: [55, 85]

    level3:
      pdf:
        dpi: 200
      process_image:
        resize_scale: 0.75

        contrast_probability: 0.95
        contrast_range: [0.9, 1.6]
        brightness_probability: 0.95
        brightness_range: [0.75, 1.1]

        crop_probability: 0.8
        crop_max_offset: [120, 120]

        rotate_probability: 0.8
        rotate_angle_range: [-10, 10]
        rotate_180_probability: 0.2

        noise_probability: 0.8
        noise_std_range: [2.5, 5.0]

        vertical_streak_probability: 0.7
        vertical_streak_width_min: 25
        vertical_streak_width_max: 90
        vertical_streak_intensity_min: 0.85
        vertical_streak_intensity_max: 1.15

        dust_probability: 0.6
        dust_count: 500
        dust_max_radius: 3

        motion_blur_probability: 0.8
        motion_blur_size_options: [7, 9, 11, 13]
        motion_blur_directions: ["horizontal", "vertical", "diag"]

        page_warp_probability: 0.8
        page_warp_amplitude: [2.0, 4.0]

        crumple_map_probability: 0.8
        crumple_map_std: 8
        crumple_map_blur_kernel: [151, 151]

        vignette_probability: 0.4
        vignette_strength: 0.6
        inverse_vignette_probability: 0.5

        paper_texture_probability: 1
        paper_texture_paths:
          - "textures/paper1.jpg"
          - "textures/paper2.jpg"
          - "textures/paper3.jpg"
        paper_texture_opacity: 0.45
        paper_texture_scale: 1.2

        jpeg_quality_range: [25, 55]


#--- ocr settings ---#
tesseract_ocr:
  lang: "eng"                             
  pdf_dpi: 300                            
  image_extensions: ['.jpg','.jpeg','.png','.tiff','.bmp']
  pdf_extension:   '.pdf'
  max_dim:           800                                       
  tesseract_cmd: "C:/Program Files/Tesseract-OCR/tesseract.exe"

easy_ocr:
  lang:
    - en
  pdf_dpi: 300                 
  image_extensions:
    - .jpg
    - .jpeg
    - .png
    - .tiff
    - .bmp
  pdf_extension: ".pdf"
  max_dim: 1024         
  
           
#--- doc-vs-drw classifier settings ---#
doc_vs_drw_classifier:
  tfidf:
    stop_words:    "english"
    max_features:  5000
  train_test_split:
    test_size:    0.2
    stratify:     true
    random_state: 41
  logistic_regression:
    max_iter:     500
    solver:       "lbfgs"
    class_weight: "balanced"
    random_state: 41


#--- doc type model settings ---#                         
doc_type_classifier:
  tfidf:
    max_features: 1000
    stop_words:   null       
  train_test_split:
    test_size:  0.2
    stratify:   true
    random_state: 41
  logistic_regression:
    max_iter:     1000
    solver:       "lbfgs"
    multi_class:  "auto"
    class_weight: "balanced"
    random_state: 41

sampling:
  docs_per_subfolder: 100  